name: Sync hbb_common and modify config

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC午夜运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
          submodules: recursive  # 包含子模块

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/rustdesk/hbb_common.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git merge upstream/main --allow-unrelated-histories

      - name: Modify src/config.rs
        run: |
          # 替换RENDEZVOUS_SERVERS
          sed -i 's|^.*RENDEZVOUS_SERVERS.*=.*&\["rs-ny.rustdesk.com"\].*$|pub const RENDEZVOUS_SERVERS: &[&str] = &["rustdesk.dp0.cc"];|' src/config.rs
          
          # 替换RS_PUB_KEY
          sed -i 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|gLTXUu5FCukGozY0Hj1ELhCKqGoxStgSXqVCTUk0tyk=|g' src/config.rs

      - name: Commit changes
        run: |
          git add src/config.rs
          git commit -m "Sync upstream and update config [skip ci]" || echo "No changes to commit"
          
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
